import { useEffect, useState } from "react";
import { Settings as SettingsApi } from "@/lib/amk-api";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { GitPullRequest, Loader2 } from "lucide-react";
import { toast } from "sonner";

export default function PRDialog({ open, onOpenChange, project, onSubmit }) {
  const [pat, setPat] = useState("");
  const [branch, setBranch] = useState("");
  const [title, setTitle] = useState("AmarktAI Network: agent-driven updates");
  const [body, setBody] = useState("This PR was generated by AmarktAI Network's autonomous agent pipeline.");
  const [savedPat, setSavedPat] = useState(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (open) {
      SettingsApi.get().then((s) => setSavedPat(s.GITHUB_PAT?.set ? s.GITHUB_PAT.preview : null));
      const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
      setBranch(`amarktai/${stamp}`);
    }
  }, [open]);

  const submit = async () => {
    setBusy(true);
    try {
      const res = await onSubmit({ github_pat: pat, branch_name: branch, title, body });
      toast.success("PR opened.", { description: `#${res.pr_number} on ${project?.github?.owner}/${project?.github?.repo}` });
      onOpenChange(false);
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to open PR");
    } finally {
      setBusy(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent data-testid="pr-dialog" className="bg-amk-panel border border-amk-line text-amk-fg max-w-lg p-0 rounded-md">
        <DialogHeader className="px-5 pt-5 pb-3 border-b border-amk-line">
          <DialogTitle className="font-mono text-sm tracking-tight uppercase">// Open Pull Request</DialogTitle>
          <DialogDescription className="font-mono text-[11px] text-amk-fg3">
            Push the agents' edits as a new branch on{" "}
            <span className="text-amk-fg">{project?.github?.owner}/{project?.github?.repo}</span> and open a PR.
          </DialogDescription>
        </DialogHeader>
        <div className="p-5 space-y-4">
          <div>
            <Label className="font-mono text-xs">GitHub Personal Access Token</Label>
            <Input
              data-testid="pr-pat-input"
              type="password"
              value={pat}
              onChange={(e) => setPat(e.target.value)}
              placeholder={savedPat ? `Using saved · ${savedPat}` : "ghp_xxxx... (needs repo + pull-request scope)"}
              className="bg-amk-base border-amk-line text-amk-fg font-mono text-xs h-9 mt-1.5 focus-visible:ring-0 focus-visible:border-white"
            />
            <p className="font-mono text-[10px] text-amk-fg3 mt-1">
              Token is sent only to the GitHub API for this request — never stored unless you save it in Settings.
            </p>
          </div>
          <div>
            <Label className="font-mono text-xs">Branch</Label>
            <Input data-testid="pr-branch-input" value={branch} onChange={(e) => setBranch(e.target.value)}
              className="bg-amk-base border-amk-line text-amk-fg font-mono text-xs h-9 mt-1.5 focus-visible:ring-0 focus-visible:border-white" />
          </div>
          <div>
            <Label className="font-mono text-xs">Title</Label>
            <Input data-testid="pr-title-input" value={title} onChange={(e) => setTitle(e.target.value)}
              className="bg-amk-base border-amk-line text-amk-fg font-mono text-xs h-9 mt-1.5 focus-visible:ring-0 focus-visible:border-white" />
          </div>
          <div>
            <Label className="font-mono text-xs">Description</Label>
            <textarea data-testid="pr-body-input" rows={4} value={body} onChange={(e) => setBody(e.target.value)}
              className="w-full bg-amk-base border border-amk-line text-amk-fg font-sans text-sm p-2.5 mt-1.5 focus:outline-none focus:border-white resize-none" />
          </div>
        </div>
        <DialogFooter className="px-5 pb-5 pt-2 border-t border-amk-line">
          <Button data-testid="pr-cancel-btn" variant="ghost" onClick={() => onOpenChange(false)}
            className="font-mono text-xs h-9 hover:bg-amk-surface">Cancel</Button>
          <Button data-testid="pr-submit-btn" onClick={submit} disabled={busy || (!pat && !savedPat)}
            className="bg-amk-accent text-black hover:bg-emerald-300 font-mono text-xs h-9">
            {busy ? <Loader2 className="w-3.5 h-3.5 animate-spin mr-1.5" /> : <GitPullRequest className="w-3.5 h-3.5 mr-1.5" strokeWidth={2} />}
            {busy ? "Opening..." : "Open PR"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
